### ISSUE TITLE
Crash on startup Fabric 1.20.1

### ISSUE THREAD

**Issue by WarmIceCream** [CursedFlames/MCTweaks#1]
You seemed to miss out the crash on startup fix for Fabric 1.20 when you updated the other versions/mod loaders

**Comment by CursedFlames** [comment]
Assuming you're referring to Split Shulker Boxes, this fix is only necessary on Forge. The only reason the Fabric backports are v1.0.1 is because I made them after doing the Forge fix.

**Comment by WarmIceCream** [comment]
Oh, I did still experience a crash on startup for 1.20.1 fabric - but maybe there's an incompatibility with another mod I was using
